#!/bin/sh
# chkconfig: 345 99 10
# description: Auto-starts tomcat
# /etc/init.d/tomcatd
# Tomcat auto-start
# Source function library.
#. /etc/init.d/functions
# source networking configuration.
#. /etc/sysconfig/network
RETVAL=0
export JAVA_HOME=/usr/local/java/jdk7
export JRE_HOME=/usr/local/java/jdk7/jre
export CATALINA_HOME=/usr/local/tomcat/apache-tomcat-8.0.52
export LOG_DIR=/usr/local/tomcat/apache-tomcat-8.0.52/logs

case "$1" in

  start)
    echo -n "Starting Tomcat:"
    /sbin/runuser -s /bin/sh root -c "nohup $CATALINA_HOME/bin/startup.sh > $LOG_DIR/tomcat.server.out 2> $LOG_DIR/tomcat.server.err &"
    echo " done."
    exit 0
    ;;

  stop)
    echo -n "Stopping Tomcat: "
    /sbin/runuser -s /bin/sh root  -c "nohup $CATALINA_HOME/bin/shutdown.sh > $LOG_DIR/tomcat.server.out 2> $LOG_DIR/tomcat.server.err &"
    echo " done."
    exit 0
    ;;
  

  status)
    c_pid=`ps -ef | grep tomcat | grep -v grep | awk '{print $2}'`
    if [ "$c_pid" = "" ] ; then
      echo "Stopped"
      exit 3
    else
      echo "Running $c_pid"
      exit 0
    fi
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "Usage: Tomcat {start|stop|status|restart}"
    exit 1
    ;;

esac


